apiVersion: v2
name: mongodb-backup
description: Database mongo backup cronjob
type: application
version: 0.2.0
appVersion: "0.2.0"
dependencies:
- name: common
  version: 1.1.0
  repository: https://sun-asterisk-research.github.io/helm-charts
